server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /contratid/ {
        try_files $uri $uri/ /contratid/index.html;
    }

    location / {
        return 301 /contratid/;
    }
}
