server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /contratid/ {
        try_files $uri $uri/ @spa;
    }

    location /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control 'public, immutable';
    }

    location = / {
        return 301 /contratid/;
    }

    location / {
        return 301 /contratid/;
    }

    location @spa {
        add_header Content-Type 'text/html; charset=utf-8';
        add_header Content-Security-Policy "frame-ancestors 'self' https://uidsoftware.com.br https://*.uidsoftware.com.br";
        root /usr/share/nginx/html;
        try_files /index.html =404;
    }
}
