# Generated by Django 5.2.15 on 2026-06-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('metodo_envio', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('link', 'Link de assinatura')], default='email', max_length=20, verbose_name='Método de envio')),
                ('autentique_public_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Public ID Autentique')),
                ('link_assinatura', models.URLField(blank=True, null=True, verbose_name='Link de assinatura')),
                ('visualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Visualizado em')),
                ('assinado_em', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('recusado_em', models.DateTimeField(blank=True, null=True, verbose_name='Recusado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatarios', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Signatário',
                'verbose_name_plural': 'Signatários',
                'ordering': ['nome'],
            },
        ),
    ]
