# Generated by Django 5.2.15 on 2026-06-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('corpo_final', models.TextField(help_text='HTML com variáveis já substituídas.', verbose_name='Corpo final')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('visualizado', 'Visualizado'), ('assinado', 'Assinado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20, verbose_name='Status')),
                ('autentique_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Autentique')),
                ('autentique_link', models.URLField(blank=True, null=True, verbose_name='Link Autentique')),
                ('arquivo_original', models.FileField(blank=True, null=True, upload_to='contratos/originais/', verbose_name='Arquivo original')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='contratos/assinados/', verbose_name='Arquivo assinado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ModeloContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Contrato Aluno Pilates', max_length=200, verbose_name='Nome')),
                ('segmento', models.CharField(max_length=100, verbose_name='Segmento')),
                ('corpo_html', models.TextField(help_text='HTML com variáveis no formato {{nome}}, {{cpf}}, etc.', verbose_name='Corpo HTML')),
                ('variaveis', models.JSONField(default=list, help_text='Lista de variáveis substituíveis no corpo do contrato.', verbose_name='Variáveis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contrato',
                'ordering': ['nome'],
            },
        ),
    ]
