# Generated by Django 5.2.15 on 2026-06-24 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='modelocontrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='contratos.modelocontrato', verbose_name='Modelo'),
        ),
    ]
